---
- name: Check if Docker is already present
  ansible.builtin.command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: docker_command_result

- name: Download Docker install convenience script
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: "0755"
  when: docker_command_result.rc != 0

- name: Run Docker install convenience script
  ansible.builtin.command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: docker_command_result.rc != 0

- name: Clean up Docker install script
  ansible.builtin.file:
    path: /tmp/get-docker.sh
    state: absent
  when: docker_command_result.rc != 0

- name: Make sure Docker CE is the version specified
  ansible.builtin.apt:
    name: "docker-ce={{ docker_version }}"
    state: present
    install_recommends: "{{ docker_install_recommends | default(false) }}"
  when: docker_version is defined and docker_version != 'latest'

- name: Ensure Docker is started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Ensure Docker Compose plugin is installed
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present
  when: docker_install_compose | default(true) | bool

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Ensure docker users are added to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users | default(['pi']) }}"
