- name: setup Duplicati
  docker_container:
    name: duplicati
    image: duplicati/duplicati:latest
    env:
       UID: "1000" #id username
       GID: "1000" #id username
       TZ: "Europe/Kiev"  
    volumes:
      - /home/pi/docker/duplicati/config:/config
      - /home/pi/docker/duplicati/backups:/backups
      - /home/pi/docker/duplicati/source:/source
    ports:
      - "8200:8200"
    restart_policy: unless-stopped