---
- name: Setup Duplicati
  community.docker.docker_container:
    name: duplicati
    image: duplicati/duplicati:latest
    env:
      UID: "{{ docker_uid }}"
      GID: "{{ docker_gid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/duplicati/config:/config"
      - "{{ docker_dir }}/duplicati/backups:/backups"
      - "{{ docker_dir }}/duplicati/source:/source"
    ports:
      - "8200:8200"
    restart_policy: unless-stopped
