---
- name: Setup Syncthing
  community.docker.docker_container:
    name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    env:
      PUID: "{{ docker_uid }}"
      PGID: "{{ docker_gid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/syncthing/config:/config"
      - "{{ docker_dir }}/syncthing/sync:/data1"
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart_policy: always
