- name: Setup FreshRSS
  docker_container:
    name: freshrss 
    image: freshrss/freshrss:latest
    env:
       PUID: "1000" #id username
       PGID: "1000" #id username
       TZ: "Europe/Kiev"
       CRON_MIN: "2,32"
       ADMIN_EMAIL: "admin@example.net"
       ADMIN_PASSWORD: "freshrss"
       ADMIN_API_PASSWORD: "freshrss"
    volumes:
      - /home/pi/docker/freshrss/data:/var/www/FreshRSS/data
      - /home/pi/docker/freshrss/extensions:/var/www/FreshRSS/extensions
    ports:
      - "9090:80" # Web UI
    restart_policy: unless-stopped
    logging:
      options:
        max-size: 10m
