---
- name: Setup Uptime Kuma
  community.docker.docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma:latest
    volumes:
      - "{{ docker_dir }}/uptime-kuma/_data:/app/data"
    ports:
      - "3001:3001"
    restart_policy: always
