---
# https://hub.docker.com/r/ich777/thunderbird
- name: Setup Thunderbird
  community.docker.docker_container:
    name: Thunderbird
    image: ich777/thunderbird
    env:
      UID: "{{ docker_uid }}"
      GID: "{{ docker_gid }}"
      THUNDERBIRD_V: "latest"
      THUNDERBIRD_LANG: "en-US"
      TURBOVNC_PARAMS: "-securitytypes none"
      CUSTOM_RES_W: "1280"
      CUSTOM_RES_H: "768"
      UMASK: "000"
      DATA_PERM: "770"
    volumes:
      - "{{ docker_dir }}/thunderbird:/thunderbird"
    ports:
      - "9080:8080"
    restart_policy: always
