- name: homebridge
  docker_container:
    name: homebridge
    image: oznu/homebridge:latest
    volumes:
      - /home/pi/docker/homebridge:/homebridge
    network_mode: host
    log_driver: json-file
    log_options:
          max-size: "10mb"
          max-file: "1"
    env:
       UID: "1000" #id username
       GID: "1000" #id username
       TZ: Europe/Kiev    
    restart_policy: always



