---
- name: AdGuard Home - DNS AdBlocking
  community.docker.docker_container:
    name: adguardhome
    image: adguard/adguardhome:latest
    volumes:
      - "{{ docker_dir }}/adguardhome/conf:/opt/adguardhome/conf"
      - "{{ docker_dir }}/adguardhome/work:/opt/adguardhome/work"
    ports:
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "853:853/tcp"
      - "3000:3000/tcp"
    restart_policy: unless-stopped
