- name: Setup speedtest
  docker_container:
    name: speedtest
    image: henrywhitaker3/speedtest-tracker:latest-arm
    volumes:
      - /home/pi/docker/speedtest:/config
    ports:
      - "8765:80"
    env:
       OOKLA_EULA_GDPR: "true"
    restart_policy: always

- name: Add daily restart cron job for speedtest container
  ansible.builtin.cron:
    name: "Restart speedtest container daily"
    minute: "0"
    hour: "0"
    job: "docker restart speedtest"
    user: "pi"

