---
- name: Setup FreshRSS
  community.docker.docker_container:
    name: freshrss
    image: freshrss/freshrss:latest
    env:
      PUID: "{{ docker_uid }}"
      PGID: "{{ docker_gid }}"
      TZ: "{{ timezone }}"
      CRON_MIN: "2,32"
      ADMIN_EMAIL: "admin@example.net"
      ADMIN_PASSWORD: "freshrss"
      ADMIN_API_PASSWORD: "freshrss"
    volumes:
      - "{{ docker_dir }}/freshrss/data:/var/www/FreshRSS/data"
      - "{{ docker_dir }}/freshrss/extensions:/var/www/FreshRSS/extensions"
    ports:
      - "9191:80"
    restart_policy: unless-stopped
