name: sync files feedly backup
on:
  push:
    paths:
    - scripts/backup_feedly/feedly_backup.py

jobs:
  deploy_feedly_backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avz --delete --chmod=755
        path: scripts/backup_feedly/feedly_backup.py
        remote_path: ${{ secrets.REMOTE_PATH_FEEDLY }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_port: ${{ secrets.REMOTE_PORT }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: scripts/backup_feedly/requirements.txt
        update-pip: "true"

    - name: executing remote ssh to setup cron
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port:  ${{ secrets.REMOTE_PORT }}
        script: sudo grep 'feedly_backup.py' /var/spool/cron/crontabs/pi || crontab -l | { cat; echo "10 20 * * 6 cd ${{ secrets.REMOTE_PATH_FEEDLY }} && python3 feedly_backup.py > /dev/null 2>&1"; } | crontab -
