name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /home/pi/scripts/
        remote_host: example.com
        remote_user: pi
        remote_port: 7722
        remote_key: ${{ secrets.DEPLOY_KEY }}
