name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print name 
      run: echo "Hello $NAME. $BUILD. ${{env.REMOTE_PORT}}"
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: 
        remote_path: ${{env.REMOTE_PATH}}
        remote_host: ${{env.REMOTE_HOST}}
        remote_user: ${{env.REMOTE_USER}}
        remote_port: ${{env.REMOTE_PORT}}
        remote_key: ${{secrets.SSH_PRIVATE_KEY}}
      

