name: sync files raspberry outage
on:
  push:
    paths:
    - scripts/raspberry_outage/raspberry_outage.py

jobs:
  deploy_raspberry_outage_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avz --delete --chmod=755
        path: scripts/raspberry_outage/raspberry_outage.py
        remote_path: ${{ secrets.REMOTE_PATH }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_port: ${{ secrets.REMOTE_PORT }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: executing remote ssh to setup cron
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port:  ${{ secrets.REMOTE_PORT }}
        script: sudo grep '/home/pi/scripts/test_inet.py' /var/spool/cron/crontabs/pi || crontab -l | { cat; echo "@reboot sleep 120 && /home/pi/scripts/test_inet.py > /dev/null 2>&1"; } | crontab -